FROM python:3.8-slim-buster

RUN apt update
RUN apt install gcc -y
RUN apt install htop

### fix user
RUN useradd -ms /bin/bash aiuser
USER aiuser
WORKDIR /home/aiuser
RUN cd /home/aiuser && mkdir workdir

WORKDIR /home/aiuser/workdir

COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

# Start the app
CMD [ "python", "-u", "app.py" ]